### ISSUE TITLE
Prompt template issue in Gemini 2.0 and 1.5 (Its an issue with Gemini API not fast agent)

### ISSUE THREAD

**Issue by usamaJ17** [evalstate/fast-agent#205]
I am facing an error on `gemini-2.0-flash` , `gemini-2.0-flash-lite` and `gemini-1.5-flash` ,  basically all models I tried below flash 2.5. 
this is the error : 
`{'error': {'code': 400, 'message': '* GenerateContentRequest.contents[23].parts: contents.parts must not be empty.\n', 'status': 'INVALID_ARGUMENT'}}`
I. think its due to some prompt template, as in langchain this issue is because of a prompt template.

**Comment by evalstate** [comment]
Which provider is this with?

**Comment by usamaJ17** [comment]
hi @evalstate  
this is with google LLM apis.. If I use. flash2.5 or pro 2.5 , it works, but If i try. to use a lower model, like flash2.0, then suddenly durring working, it throw this error..

**Comment by usamaJ17** [comment]
And after I updated fast agent version, flash 2.5 pro is not. working as well

**Comment by usamaJ17** [comment]
This is. the. error trace:


Traceback (most recent call last):
  File "/Users/my_user/fast-agent/main.py", line 30, in <module>
    asyncio.run(main())
    ~~~~~~~~~~~^^^^^^^^
  File "/usr/local/Cellar/python@3.13/3.13.2/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/runners.py", line 195, in run
    return runner.run(main)
           ~~~~~~~~~~^^^^^^
  File "/usr/local/Cellar/python@3.13/3.13.2/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/usr/local/Cellar/python@3.13/3.13.2/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/base_events.py", line 725, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "/Users/my_user/fast-agent/main.py", line 26, in main
    await agent.interactive()
  File "/Users/my_user/fast-agent/.venv/lib/python3.13/site-packages/mcp_agent/core/agent_app.py", line 267, in interactive
    return await prompt.prompt_loop(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "/Users/my_user/fast-agent/.venv/lib/python3.13/site-packages/mcp_agent/core/interactive_prompt.py", line 182, in prompt_loop
    result = await send_func(user_input, agent)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/my_user/fast-agent/.venv/lib/python3.13/site-packages/mcp_agent/core/agent_app.py", line 264, in send_wrapper
    return await self.send(message, agent_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/my_user/fast-agent/.venv/lib/python3.13/site-packages/mcp_agent/core/agent_app.py", line 92, in send
    return await self._agent(agent_name).send(message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/my_user/fast-agent/.venv/lib/python3.13/site-packages/mcp_agent/agents/base_agent.py", line 225, in send
    response = await self.generate([prompt], None)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/my_user/fast-agent/.venv/lib/python3.13/site-packages/mcp_agent/agents/base_agent.py", line 596, in generate
    return await self._llm.generate(multipart_messages, request_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/my_user/fast-agent/.venv/lib/python3.13/site-packages/mcp_agent/llm/augmented_llm.py", line 212, in generate
    assistant_response: PromptMessageMultipart = await self._apply_prompt_provider_specific(
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        multipart_messages, request_params
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/my_user/fast-agent/.venv/lib/python3.13/site-packages/mcp_agent/llm/providers/augmented_llm_google_native.py", line 419, in _apply_prompt_provider_specific
    responses = await self._google_completion(request_params=request_params)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/my_user/fast-agent/.venv/lib/python3.13/site-packages/mcp_agent/llm/providers/augmented_llm_google_native.py", line 389, in _google_completion
    new_multipart_messages = self._converter.convert_from_google_content_list(
        new_google_messages
    )
  File "/Users/my_user/fast-agent/.venv/lib/python3.13/site-packages/mcp_agent/llm/providers/google_converter.py", line 334, in convert_from_google_content_list
    return [self._convert_from_google_content(content) for content in contents]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/my_user/fast-agent/.venv/lib/python3.13/site-packages/mcp_agent/llm/providers/google_converter.py", line 346, in _convert_from_google_content
    for part in content.parts:
                ^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable

**Comment by evalstate** [comment]
If you are able, can you try merging this PR: https://github.com/evalstate/fast-agent/pull/215 
The other option is to switch to the OpenAI compatible endpoint using `googleoai` as the provider (and update the API key/config file to be GOOGLEOAI_API_KEY).

**Comment by usamaJ17** [comment]
hi @evalstate 
I cant merge this PR, as I don’t have the required permission.  I tried again with gemini flash 2.0 and again got the same error.. even though I am now on updated version. 
still this error

  File "/Users/usama.jalal/bucket-mcp/fast-agent/.venv/lib/python3.11/site-packages/mcp_agent/llm/providers/google_converter.py", line 346, in _convert_from_google_content
    for part in content.parts:
TypeError: 'NoneType' object is not iterable

i would be happy to merge this PR and try again.. but I don’t  have required permissions
Edit : even with this PR (I updated that PR code to my local) getting same error

**Comment by usamaJ17** [comment]
This is the complete error log: (got that again. sometimes it works sometime not)

Traceback (most recent call last):
  File "/Users/usama.jalal/bucket-mcp/fast-agent/main.py", line 30, in <module>
    asyncio.run(main())
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/usama.jalal/bucket-mcp/fast-agent/main.py", line 26, in main
    await agent.interactive()
  File "/Users/usama.jalal/bucket-mcp/fast-agent/.venv/lib/python3.11/site-packages/mcp_agent/core/agent_app.py", line 285, in interactive
    return await prompt.prompt_loop(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/usama.jalal/bucket-mcp/fast-agent/.venv/lib/python3.11/site-packages/mcp_agent/core/interactive_prompt.py", line 209, in prompt_loop
    result = await send_func(user_input, agent)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/usama.jalal/bucket-mcp/fast-agent/.venv/lib/python3.11/site-packages/mcp_agent/core/agent_app.py", line 277, in send_wrapper
    result = await self.send(message, agent_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/usama.jalal/bucket-mcp/fast-agent/.venv/lib/python3.11/site-packages/mcp_agent/core/agent_app.py", line 94, in send
    return await self._agent(agent_name).send(message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/usama.jalal/bucket-mcp/fast-agent/.venv/lib/python3.11/site-packages/mcp_agent/agents/base_agent.py", line 226, in send
    response = await self.generate([prompt], None)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/usama.jalal/bucket-mcp/fast-agent/.venv/lib/python3.11/site-packages/mcp_agent/agents/base_agent.py", line 597, in generate
    return await self._llm.generate(multipart_messages, request_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/usama.jalal/bucket-mcp/fast-agent/.venv/lib/python3.11/site-packages/mcp_agent/llm/augmented_llm.py", line 223, in generate
    assistant_response: PromptMessageMultipart = await self._apply_prompt_provider_specific(
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/usama.jalal/bucket-mcp/fast-agent/.venv/lib/python3.11/site-packages/mcp_agent/llm/providers/augmented_llm_google_native.py", line 453, in _apply_prompt_provider_specific
    responses = await self._google_completion(request_params=request_params)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/usama.jalal/bucket-mcp/fast-agent/.venv/lib/python3.11/site-packages/mcp_agent/llm/providers/augmented_llm_google_native.py", line 423, in _google_completion
    new_multipart_messages = self._converter.convert_from_google_content_list(
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/usama.jalal/bucket-mcp/fast-agent/.venv/lib/python3.11/site-packages/mcp_agent/llm/providers/google_converter.py", line 334, in convert_from_google_content_list
    return [self._convert_from_google_content(content) for content in contents]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/usama.jalal/bucket-mcp/fast-agent/.venv/lib/python3.11/site-packages/mcp_agent/llm/providers/google_converter.py", line 334, in <listcomp>
    return [self._convert_from_google_content(content) for content in contents]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/usama.jalal/bucket-mcp/fast-agent/.venv/lib/python3.11/site-packages/mcp_agent/llm/providers/google_converter.py", line 340, in _convert_from_google_content
    if content.role == "model" and any(part.function_call for part in content.parts):
       ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'role'

**Comment by usamaJ17** [comment]
@evalstate 
any update in this?? this error is very teasing.. and I am getting this multiple times..

**Comment by usamaJ17** [comment]
@monotykamary  @evalstate 
even after merging PR, still face error.. I have observed that error is from this line
// google_converter.py (around line 474)
`if content.role == "model" and any(part.function_call for part in content.parts):`

if there is a tool call.. and tool returns some data.. `content` is `None`.. and in that case using `content.role` results in :
`AttributeError: 'NoneType' object has no attribute 'role'`

**Comment by evalstate** [comment]
Thanks @usamaJ17 I've been wanting a reproducible test case before changing (need to keep track of all the provider specific tweaks!) and that info helps. 

Does this happen with both the new native and legacy oai providers?

**Comment by usamaJ17** [comment]
hi @evalstate , what I have observed, I am getting this on gemini API. I tried 2.5 flash lite and  2.5 flash as well.. getting that error on both. 
also what I observe, I face this error while using filesystem tools, I am using [This Filesysem MCP](https://github.com/modelcontextprotocol/servers/tree/main/src/filesystem) 
i tried to go down into code to fix these.. but I ddnt get a very clear idea of what can be the issue,, I tried to filter None from content array, that doesnot throw error, but it also doesnot gave me proper message on console.,. (and I was shown input in console, but without any message) .
that main issue is, when i checked logs `MALFORMED_FUNCTION_CALL` is the cause of final API failure, and in contents array in gemini API response, last index was None. it was supposed to be an object, but in response it was None,. and that why we got the error when we tried to get attribute of none, removing None from array also ddnt helped,. it ddnt throw error, but just stoped the execution..

**Comment by usamaJ17** [comment]
@evalstate  , also I get this as well

Traceback (most recent call last):
  File "/Users/usama.jalal/bucket-mcp/fast-agent/main.py", line 30, in <module>
    asyncio.run(main())
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/usama.jalal/bucket-mcp/fast-agent/main.py", line 26, in main
    await agent.interactive()
  File "/Users/usama.jalal/bucket-mcp/fast-agent/.venv/lib/python3.11/site-packages/mcp_agent/core/agent_app.py", line 285, in interactive
    return await prompt.prompt_loop(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/usama.jalal/bucket-mcp/fast-agent/.venv/lib/python3.11/site-packages/mcp_agent/core/interactive_prompt.py", line 209, in prompt_loop
    result = await send_func(user_input, agent)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/usama.jalal/bucket-mcp/fast-agent/.venv/lib/python3.11/site-packages/mcp_agent/core/agent_app.py", line 277, in send_wrapper
    result = await self.send(message, agent_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/usama.jalal/bucket-mcp/fast-agent/.venv/lib/python3.11/site-packages/mcp_agent/core/agent_app.py", line 94, in send
    return await self._agent(agent_name).send(message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/usama.jalal/bucket-mcp/fast-agent/.venv/lib/python3.11/site-packages/mcp_agent/agents/base_agent.py", line 226, in send
    response = await self.generate([prompt], None)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/usama.jalal/bucket-mcp/fast-agent/.venv/lib/python3.11/site-packages/mcp_agent/agents/base_agent.py", line 597, in generate
    return await self._llm.generate(multipart_messages, request_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/usama.jalal/bucket-mcp/fast-agent/.venv/lib/python3.11/site-packages/mcp_agent/llm/augmented_llm.py", line 223, in generate
    assistant_response: PromptMessageMultipart = await self._apply_prompt_provider_specific(
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/usama.jalal/bucket-mcp/fast-agent/.venv/lib/python3.11/site-packages/mcp_agent/llm/providers/augmented_llm_google_native.py", line 430, in _apply_prompt_provider_specific
    responses = await self._google_completion(request_params=request_params)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/usama.jalal/bucket-mcp/fast-agent/.venv/lib/python3.11/site-packages/mcp_agent/llm/providers/augmented_llm_google_native.py", line 400, in _google_completion
    new_multipart_messages = self._converter.convert_from_google_content_list(
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/usama.jalal/bucket-mcp/fast-agent/.venv/lib/python3.11/site-packages/mcp_agent/llm/providers/google_converter.py", line 465, in convert_from_google_content_list
    return [self._convert_from_google_content(content) for content in contents]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/usama.jalal/bucket-mcp/fast-agent/.venv/lib/python3.11/site-packages/mcp_agent/llm/providers/google_converter.py", line 465, in <listcomp>
    return [self._convert_from_google_content(content) for content in contents]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/usama.jalal/bucket-mcp/fast-agent/.venv/lib/python3.11/site-packages/mcp_agent/llm/providers/google_converter.py", line 474, in _convert_from_google_content
    if content.role == "model" and any(part.function_call for part in content.parts):
       ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'role'

**Comment by usamaJ17** [comment]
@evalstate  , I was trying to fix that, but whats seems like, its not in our framework, its in google genai . 
you can review this issue : https://github.com/googleapis/python-aiplatform/issues/4472 , as its mention in this as well, that they have migrated to google Gen AI SDK, instead of Vertex Ai SDK, BUT, this framework is using google GEN AI SDK , so the actual issue is I think This : https://github.com/googleapis/python-genai/issues/430 , because what I observered, it almost always occurs while writing final output to a file, and that output is a bit long.. not too much, but like around 150 lines of text.

**Comment by evalstate** [comment]
Great detective work... My guess from that discussion is that there is a templating issue on their end (some sequence cuasing a parsing error). The only thing I can think of is to attempt to prompt around it (e.g. experiment with "DONT USE BACKTICKS" or "ENCLOSE FILE DATA IN XML TAGS") and see if that calms it down. Are you able to share a program that does this regularly that I can just run?

**Comment by usamaJ17** [comment]
@evalstate, yes, I was trying to add that to the agent instruction to not write the complete file, but write in chunks. No success for now, but I will try to find a way. Also, should I add that to the agent instruction? 
And sorry, I am unable to share that because I don't have a proper sample for it. I have created one agent that creates some data in text form and writes that to a file. I think you can try an agent that creates a long essay and writes that to a file.

**Comment by evalstate** [comment]
This is going wrong generating the Tool Call right (so the model is making malformed calls)? 

In which case the LLM is completing inference, and the API is then attempting to force the result to JSON and failing (hence the message). Fixing goes 2 ways (without access to their API internals...)

1) Figuring out what sequence of characters is causing the JSON coercion to fail when presenting the Tool Call (to get round whatever parsing issue keeps recurring).
2) Detecting that error condition on the Client side (e.g. `fast-agent`) and running another generation or 2 in the hope it doesn't trigger the error.

**Comment by usamaJ17** [comment]
Yes, model is making incorrect calls, thats why we are not getting response , and the reason returned from gemini is `MALFORMED_FUNCTION_CALL` as well. 
I don’t think 2 will be helpful , as until  now LLM is working hard to always throw that error, so I think even a loop cant help, I was trying to get contents in chunks , but thats still failing.

**Comment by evalstate** [comment]
Only other thing is if this gets worse with context length? Is it possible to use `apply_prompt` and `use_history=False` to have the Agent produce what it needs? Else I think we simply have a bad model....

**Comment by usamaJ17** [comment]
@evalstate  I dont think `apply_prompt` will help. I can try with use_history=False , but i am very confident that this will cause error as well. I changed prompt, ask LLM to not generate or return all data at once, but generate sections, and write file in multiple calls. That helps a bit, but mainly thats a model issue.

**Comment by hd24-jspoerer** [comment]
@usamaJ17 @janspoerer 

Thanks for pointing this out in https://github.com/evalstate/fast-agent/issues/207#issuecomment-3112732798.

> hi @hd24-jspoerer , can you also look into this https://github.com/evalstate/fast-agent/issues/205 Thanks

Is this still relevant, as now you've received an answer here?

From what I can gather from the latest messages, this is not an issue on our end? Should we wait for an upstream fix of the API (or the SDK, not sure where this error originates from by just skimming over the comments)?

**Comment by usamaJ17** [comment]
Hi @hd24-jspoerer , thanks for your response, Yes that not an issue from framework. Its an issue with gemini API, I switched to openAI GPT4.1 and that works fine.
