### ISSUE TITLE
Unexpected keyword argument 'progress_callback'"

### ISSUE THREAD

**Issue by bradenmacdonald** [evalstate/fast-agent#175]
`fast-agent` doesn't seem to work with the recently-released `mcp==1.9.0`. Because of [this change](https://github.com/modelcontextprotocol/python-sdk/pull/721) (I think), now running an agent gives this error:

```
MCPAgentClientSession.send_request() got an unexpected keyword argument 'progress_callback'
```

I believe [this code](https://github.com/evalstate/fast-agent/blob/da55c89445108f3303b9a424eead6be17a72fbc2/src/mcp_agent/mcp/mcp_agent_client_session.py#L73-L78) needs to be updated to accept the new parameter.

For now I downgraded to `mcp==1.8.0` and it works around the problem.

**Comment by gitanon112** [comment]
+1

**Comment by evalstate** [comment]
Thanks - I did a quick patch release to 0.2.26 which pinned 1.8.0 - will upgrade properly in the next release (and pin @ 1.9.0!)
